project:
  type: website

website:
  page-navigation: true
  title: "PSC 2339--Fall Schedule"
  description: "Homepage for PSC 2339 - Comparative Political Economy, George Washington University."
  site-url: "https://psc2339/fall-2022"

  #repo-url: https://github.com/psc2339-fall
  #repo-actions: [edit, issue]

  open-graph: true
  favicon: "images/cpe_logo.png"
  twitter-card: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/). üë∑üõ†Ô∏è"
    left: "&copy; Copyright 2022, [Emmanuel Teitelbaum](https://emmanuel.teitelbaum.com)"
    background: "#A4DBF5"

  sidebar:
    background: "#A4DBF5"
    logo: "images/cpe_logo.png"
    pinned: true
    align: center
    tools:
      - icon: mortarboard-fill
        text: "Blackboard"
        href: https://blackboard.gwu.edu
      - icon: bar-chart-fill
        href: https://library.gwu.edu/work-data
        text: "Gelman Data Services"
      - icon: microsoft
        href: https://it.gwu.edu/microsoft-365
        text: "Microsoft 365"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-description.qmd
            text: Description
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: instructor.qmd
            text: Instructor
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: faq.qmd
            text: FAQ
      - section: "Project"
        contents:
           #- href: project-description.qmd
            # text: Description
          - href: project/project-assignment-1.qmd
            text: "Assignment 1"
          - href: project/project-assignment-2.qmd
            text: "Assignment 2"
          - href: project/project-assignment-3.qmd
            text: "Assignment 3"
          - href: project/project-datasets.qmd
            text: Datasets
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
          - href: weeks/week-7.qmd
            text: "Week 7"
          - href: weeks/week-8.qmd
            text: "Week 8"
          - href: weeks/week-9.qmd
            text: "Week 9"
          - href: weeks/week-10.qmd
            text: "Week 10"
          - href: weeks/week-11.qmd
            text: "Week 11"
          - href: weeks/week-12.qmd
            text: "Week 12"
          - href: weeks/week-13.qmd
            text: "Week 13"
          - href: weeks/week-14.qmd
            text: "Week 14"
          - href: weeks/week-15.qmd
            text: "Week 15"
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: source